begin;

create table if not exists public.trivias (
  id bigint generated by default as identity primary key,
  content text not null,
  publish_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trivias_content_check check (
    char_length(btrim(content)) between 1 and 1000
  ),
  constraint trivias_publish_date_key unique (publish_date)
);

create index if not exists trivias_publish_date_idx
  on public.trivias(publish_date, id);

create or replace function public.validate_trivia_publish_date()
returns trigger
language plpgsql
set search_path = ''
set timezone = 'Asia/Manila'
as $$
begin
  if new.publish_date < current_date
    and (tg_op = 'INSERT' or new.publish_date is distinct from old.publish_date)
  then
    raise exception 'Publish date cannot be in the past'
      using errcode = '22007';
  end if;

  return new;
end;
$$;

drop trigger if exists validate_trivia_publish_date on public.trivias;
create trigger validate_trivia_publish_date
before insert or update of publish_date on public.trivias
for each row execute function public.validate_trivia_publish_date();

drop trigger if exists set_trivias_updated_at on public.trivias;
create trigger set_trivias_updated_at
before update on public.trivias
for each row execute function public.set_updated_at();

alter table public.trivias enable row level security;

drop policy if exists "Authenticated users can view trivias" on public.trivias;
drop policy if exists "Reviewees can view today's trivia" on public.trivias;
create policy "Reviewees can view today's trivia"
on public.trivias
for select
to authenticated
using (
  publish_date = (current_timestamp at time zone 'Asia/Manila')::date
  and 'reviewee' = any(public.get_user_roles((select auth.uid())))
);

drop policy if exists "Admins can manage trivias" on public.trivias;
create policy "Admins can manage trivias"
on public.trivias
for all
to authenticated
using (
  'admin' = any(public.get_user_roles((select auth.uid())))
)
with check (
  'admin' = any(public.get_user_roles((select auth.uid())))
);

drop policy if exists "Admins can create trivias" on public.trivias;
drop policy if exists "Admins can update trivias" on public.trivias;
drop policy if exists "Admins can delete trivias" on public.trivias;

revoke all on table public.trivias from public, anon, authenticated;
grant select, insert, update, delete on table public.trivias to authenticated;
grant all on table public.trivias to service_role;

revoke all on sequence public.trivias_id_seq from public, anon, authenticated;
grant usage, select on sequence public.trivias_id_seq to authenticated;
grant all on sequence public.trivias_id_seq to service_role;

revoke all on function public.validate_trivia_publish_date()
  from public, anon, authenticated;

commit;
