begin;

lock table public.quiz_timer_configurations in share row exclusive mode;

alter table public.quiz_timer_configurations
  add column if not exists id bigint generated by default as identity;

update public.quiz_timer_configurations
set id = default
where id is null;

alter table public.quiz_timer_configurations
  alter column id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conrelid = 'public.quiz_timer_configurations'::regclass
      and contype = 'p'
  ) then
    alter table public.quiz_timer_configurations
      add constraint quiz_timer_configurations_pkey primary key (id);
  end if;
end;
$$;

alter table public.quiz_timer_configurations
  drop constraint if exists quiz_timer_configurations_game_type_check,
  drop constraint if exists quiz_timer_configurations_difficulty_check;

alter table public.quiz_timer_configurations
  add constraint quiz_timer_configurations_game_type_check check (
    game_type in (
      'Guess the Word',
      'AB-Solution',
      'Situationship',
      'PAES',
      'Flash Cards'
    )
  ),
  add constraint quiz_timer_configurations_difficulty_check check (
    (game_type in ('PAES', 'Flash Cards') and difficulty is null)
    or (
      game_type in ('Guess the Word', 'AB-Solution', 'Situationship')
      and difficulty in ('Easy', 'Medium', 'Hard')
    )
  );

insert into public.quiz_timer_configurations (
  game_type,
  difficulty,
  timer_seconds
)
values ('Flash Cards', null, 15)
on conflict (game_type, (coalesce(difficulty, '')))
do nothing;

alter table public.game_sessions
  drop constraint if exists game_sessions_flash_card_timer_check;

alter table public.game_sessions
  add constraint game_sessions_flash_card_timer_check check (
    session_type <> 'flash_cards'
    or timer_seconds > 0
  );

create or replace function public.prepare_flash_card_session(
  selected_area_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_deck public.flash_card_decks%rowtype;
  selected_area_name text;
  selected_timer_seconds smallint;
  created_session_id uuid;
  created_session_flash_card_id bigint;
  flash_card_number integer := 0;
  selected_flash_card record;
  prepared_flash_cards jsonb;
begin
  authenticated_user_id := public.flash_card_reviewee_user_id();
  selected_timer_seconds := public.quiz_timer_seconds('Flash Cards', null);

  if selected_timer_seconds is null then
    raise exception 'A Flash Cards timer configuration is required'
      using errcode = '22023';
  end if;

  select flash_card_decks.*
  into selected_deck
  from public.flash_card_decks
  where flash_card_decks.user_id = authenticated_user_id
    and flash_card_decks.area_id = selected_area_id;

  if not found then
    return jsonb_build_object('status', 'empty');
  end if;

  select subject_areas.name
  into selected_area_name
  from public.subject_areas
  where subject_areas.id = selected_area_id;

  if not found then
    raise exception 'A valid subject area is required'
      using errcode = '22023';
  end if;

  insert into public.game_sessions (
    user_id,
    area_id,
    area_name,
    session_type,
    flash_card_deck_id,
    game_type,
    difficulty,
    timer_seconds
  )
  values (
    authenticated_user_id,
    selected_area_id,
    selected_area_name,
    'flash_cards',
    selected_deck.id,
    'Flash Cards',
    null,
    selected_timer_seconds
  )
  returning id into created_session_id;

  for selected_flash_card in
    select
      flash_cards.id,
      flash_cards.question,
      flash_cards.answer
    from public.flash_cards
    where flash_cards.deck_id = selected_deck.id
    order by random()
  loop
    flash_card_number := flash_card_number + 1;

    insert into public.game_session_flash_cards (
      session_id,
      flash_card_id,
      question_text,
      card_order
    )
    values (
      created_session_id,
      selected_flash_card.id,
      selected_flash_card.question,
      flash_card_number
    )
    returning id into created_session_flash_card_id;

    insert into public.game_session_flash_card_answer_keys (
      session_flash_card_id,
      correct_answer
    )
    values (
      created_session_flash_card_id,
      selected_flash_card.answer
    );
  end loop;

  if flash_card_number = 0 then
    delete from public.game_sessions
    where id = created_session_id;

    return jsonb_build_object('status', 'empty');
  end if;

  update public.game_sessions
  set total_questions = flash_card_number
  where id = created_session_id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'sessionFlashCardId', game_session_flash_cards.id,
        'cardOrder', game_session_flash_cards.card_order,
        'questionText', game_session_flash_cards.question_text
      )
      order by game_session_flash_cards.card_order
    ),
    '[]'::jsonb
  )
  into prepared_flash_cards
  from public.game_session_flash_cards
  where game_session_flash_cards.session_id = created_session_id;

  return jsonb_build_object(
    'status', 'prepared',
    'sessionId', created_session_id,
    'areaId', selected_area_id,
    'areaName', selected_area_name,
    'timerSeconds', selected_timer_seconds,
    'totalFlashCards', flash_card_number,
    'flashCards', prepared_flash_cards
  );
end;
$$;

create or replace function public.preview_flash_card_session(
  selected_area_id bigint
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_deck_id bigint;
  selected_area_name text;
  available_flash_card_count integer;
  selected_timer_seconds smallint;
begin
  authenticated_user_id := public.flash_card_reviewee_user_id();
  selected_timer_seconds := public.quiz_timer_seconds('Flash Cards', null);

  if selected_timer_seconds is null then
    raise exception 'A Flash Cards timer configuration is required'
      using errcode = '22023';
  end if;

  select
    flash_card_decks.id,
    subject_areas.name
  into
    selected_deck_id,
    selected_area_name
  from public.flash_card_decks
  join public.subject_areas
    on subject_areas.id = flash_card_decks.area_id
  where flash_card_decks.user_id = authenticated_user_id
    and flash_card_decks.area_id = selected_area_id;

  if not found then
    return jsonb_build_object('status', 'empty');
  end if;

  select count(*)::integer
  into available_flash_card_count
  from public.flash_cards
  where flash_cards.deck_id = selected_deck_id;

  if available_flash_card_count = 0 then
    return jsonb_build_object('status', 'empty');
  end if;

  return jsonb_build_object(
    'status', 'available',
    'areaId', selected_area_id,
    'areaName', selected_area_name,
    'timerSeconds', selected_timer_seconds,
    'totalFlashCards', available_flash_card_count
  );
end;
$$;

revoke all on function public.prepare_flash_card_session(bigint)
  from public, anon, authenticated;
revoke all on function public.preview_flash_card_session(bigint)
  from public, anon, authenticated;

grant execute on function public.prepare_flash_card_session(bigint)
  to authenticated;
grant execute on function public.preview_flash_card_session(bigint)
  to authenticated;

commit;
