begin;

create table if not exists public.activity_history (
  id bigint generated by default as identity primary key,
  game_session_id uuid not null unique
    references public.game_sessions(id) on delete cascade,
  user_id uuid not null references public.users(user_id) on delete cascade,
  session_type text not null,
  area_id bigint,
  area_name text not null,
  game_type text not null,
  difficulty text,
  status text not null,
  end_reason text not null,
  total_questions integer not null,
  correct_count integer not null,
  incorrect_count integer not null,
  timed_out_count integer not null,
  not_played_count integer not null,
  questions_reached_count integer not null,
  answered_count integer not null,
  accuracy_percentage numeric(5, 2) not null,
  completion_percentage numeric(5, 2) not null,
  duration_seconds integer not null,
  prepared_at timestamptz not null,
  started_at timestamptz,
  terminal_at timestamptz not null,
  updated_at timestamptz not null default now(),
  constraint activity_history_session_type_check check (
    session_type in ('mcq_quiz', 'flash_cards')
  ),
  constraint activity_history_status_check check (
    status in ('completed', 'exited', 'cancelled')
  ),
  constraint activity_history_end_reason_check check (
    end_reason in ('completed', 'user_exit', 'countdown_cancelled')
  ),
  constraint activity_history_counts_check check (
    total_questions >= 0
    and correct_count >= 0
    and incorrect_count >= 0
    and timed_out_count >= 0
    and not_played_count >= 0
    and questions_reached_count >= 0
    and answered_count >= 0
    and duration_seconds >= 0
  ),
  constraint activity_history_percentages_check check (
    accuracy_percentage between 0 and 100
    and completion_percentage between 0 and 100
  )
);

create index if not exists activity_history_user_terminal_at_idx
  on public.activity_history(user_id, terminal_at desc, id desc);

create index if not exists activity_history_user_session_type_idx
  on public.activity_history(user_id, session_type, terminal_at desc);

create index if not exists activity_history_user_game_type_idx
  on public.activity_history(user_id, game_type, terminal_at desc);

create index if not exists activity_history_user_status_idx
  on public.activity_history(user_id, status, terminal_at desc);

alter table public.activity_history enable row level security;

drop policy if exists "Reviewees can view their activity history"
  on public.activity_history;
create policy "Reviewees can view their activity history"
on public.activity_history
for select
to authenticated
using (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.user_roles
    join public.roles on roles.id = user_roles.role_id
    where user_roles.user_id = (select auth.uid())
      and roles.name = 'reviewee'
  )
);

revoke all on table public.activity_history
  from public, anon, authenticated;
grant select on table public.activity_history to authenticated;
grant all on table public.activity_history to service_role;

revoke all on sequence public.activity_history_id_seq
  from public, anon, authenticated;
grant all on sequence public.activity_history_id_seq to service_role;

create or replace function public.sync_activity_history_session(
  selected_session_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_session public.game_sessions%rowtype;
  correct_count integer := 0;
  incorrect_count integer := 0;
  timed_out_count integer := 0;
  not_played_count integer := 0;
  questions_reached_count integer := 0;
  answered_count integer := 0;
  completed_item_count integer := 0;
  accuracy_percentage numeric(5, 2) := 0;
  completion_percentage numeric(5, 2) := 0;
  duration_seconds integer := 0;
begin
  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id;

  if not found or selected_session.status not in (
    'completed',
    'exited',
    'cancelled'
  ) then
    return;
  end if;

  if selected_session.session_type = 'flash_cards' then
    select
      count(*) filter (where result = 'correct'),
      count(*) filter (where result = 'incorrect'),
      count(*) filter (where status = 'timed_out'),
      count(*) filter (
        where status in ('abandoned', 'not_played', 'cancelled')
      ),
      count(*) filter (
        where status in (
          'active',
          'submitted',
          'answered',
          'timed_out',
          'abandoned'
        )
      )
    into
      correct_count,
      incorrect_count,
      timed_out_count,
      not_played_count,
      questions_reached_count
    from public.game_session_flash_cards
    where session_id = selected_session_id;
  else
    select
      count(*) filter (where result = 'correct'),
      count(*) filter (where result = 'incorrect'),
      count(*) filter (where status = 'timed_out'),
      count(*) filter (
        where status in ('abandoned', 'not_played', 'cancelled')
      ),
      count(*) filter (
        where status in (
          'active',
          'submitted',
          'answered',
          'timed_out',
          'abandoned'
        )
      )
    into
      correct_count,
      incorrect_count,
      timed_out_count,
      not_played_count,
      questions_reached_count
    from public.game_session_questions
    where session_id = selected_session_id;
  end if;

  answered_count := correct_count + incorrect_count;
  completed_item_count := answered_count + timed_out_count;

  accuracy_percentage := case
    when answered_count = 0 then 0
    else round(
      (correct_count::numeric / answered_count::numeric) * 100,
      2
    )
  end;

  completion_percentage := case
    when selected_session.total_questions = 0 then 0
    else round(
      (
        completed_item_count::numeric
        / selected_session.total_questions::numeric
      ) * 100,
      2
    )
  end;

  duration_seconds := case
    when selected_session.started_at is null then 0
    else greatest(
      0,
      floor(
        extract(
          epoch from (
            coalesce(selected_session.ended_at, clock_timestamp())
            - selected_session.started_at
          )
        )
      )::integer
    )
  end;

  insert into public.activity_history (
    game_session_id,
    user_id,
    session_type,
    area_id,
    area_name,
    game_type,
    difficulty,
    status,
    end_reason,
    total_questions,
    correct_count,
    incorrect_count,
    timed_out_count,
    not_played_count,
    questions_reached_count,
    answered_count,
    accuracy_percentage,
    completion_percentage,
    duration_seconds,
    prepared_at,
    started_at,
    terminal_at,
    updated_at
  )
  values (
    selected_session.id,
    selected_session.user_id,
    selected_session.session_type,
    selected_session.area_id,
    selected_session.area_name,
    selected_session.game_type,
    selected_session.difficulty,
    selected_session.status,
    coalesce(selected_session.end_reason, 'completed'),
    selected_session.total_questions,
    correct_count,
    incorrect_count,
    timed_out_count,
    not_played_count,
    questions_reached_count,
    answered_count,
    accuracy_percentage,
    completion_percentage,
    duration_seconds,
    selected_session.prepared_at,
    selected_session.started_at,
    coalesce(selected_session.ended_at, selected_session.prepared_at),
    clock_timestamp()
  )
  on conflict (game_session_id) do update
  set
    user_id = excluded.user_id,
    session_type = excluded.session_type,
    area_id = excluded.area_id,
    area_name = excluded.area_name,
    game_type = excluded.game_type,
    difficulty = excluded.difficulty,
    status = excluded.status,
    end_reason = excluded.end_reason,
    total_questions = excluded.total_questions,
    correct_count = excluded.correct_count,
    incorrect_count = excluded.incorrect_count,
    timed_out_count = excluded.timed_out_count,
    not_played_count = excluded.not_played_count,
    questions_reached_count = excluded.questions_reached_count,
    answered_count = excluded.answered_count,
    accuracy_percentage = excluded.accuracy_percentage,
    completion_percentage = excluded.completion_percentage,
    duration_seconds = excluded.duration_seconds,
    prepared_at = excluded.prepared_at,
    started_at = excluded.started_at,
    terminal_at = excluded.terminal_at,
    updated_at = excluded.updated_at;
end;
$$;

create or replace function public.sync_activity_history()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.sync_activity_history_session(new.id);
  return new;
end;
$$;

drop trigger if exists sync_activity_history on public.game_sessions;
create trigger sync_activity_history
after insert or update on public.game_sessions
for each row
when (new.status in ('completed', 'exited', 'cancelled'))
execute function public.sync_activity_history();

do $$
declare
  terminal_session record;
begin
  for terminal_session in
    select game_sessions.id
    from public.game_sessions
    where game_sessions.status in ('completed', 'exited', 'cancelled')
  loop
    perform public.sync_activity_history_session(terminal_session.id);
  end loop;
end;
$$;

create or replace function public.get_activity_history_details(
  selected_history_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_history public.activity_history%rowtype;
  history_items jsonb;
begin
  authenticated_user_id := auth.uid();

  if authenticated_user_id is null then
    raise exception 'You must be logged in to view activity history'
      using errcode = '42501';
  end if;

  select activity_history.*
  into selected_history
  from public.activity_history
  where activity_history.id = selected_history_id
    and activity_history.user_id = authenticated_user_id;

  if not found then
    raise exception 'Activity history was not found'
      using errcode = 'P0002';
  end if;

  if selected_history.session_type = 'flash_cards' then
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'sessionType', 'flash_cards',
          'id', session_flash_card.id,
          'order', session_flash_card.card_order,
          'prompt', session_flash_card.question_text,
          'submittedAnswer', session_flash_card.submitted_answer,
          'correctAnswer', answer_key.correct_answer,
          'status', session_flash_card.status,
          'result', session_flash_card.result,
          'presentedAt', session_flash_card.presented_at,
          'deadlineAt', session_flash_card.deadline_at,
          'submittedAt', session_flash_card.submitted_at,
          'revealAt', session_flash_card.reveal_at,
          'resolvedAt', session_flash_card.resolved_at,
          'responseTimeMs', session_flash_card.response_time_ms
        )
        order by session_flash_card.card_order
      ),
      '[]'::jsonb
    )
    into history_items
    from public.game_session_flash_cards as session_flash_card
    join public.game_session_flash_card_answer_keys as answer_key
      on answer_key.session_flash_card_id = session_flash_card.id
    where session_flash_card.session_id = selected_history.game_session_id;
  else
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'sessionType', 'mcq_quiz',
          'id', session_question.id,
          'order', session_question.question_order,
          'subjectName', session_question.subject_name,
          'prompt', session_question.question_text,
          'options', session_question.options,
          'selectedOption', (
            select quiz_option
            from jsonb_array_elements(session_question.options) as quiz_option
            where (quiz_option ->> 'id')::bigint =
              session_question.selected_option_id
          ),
          'correctOption', (
            select quiz_option
            from jsonb_array_elements(session_question.options) as quiz_option
            where (quiz_option ->> 'id')::bigint =
              answer_key.correct_option_id
          ),
          'status', session_question.status,
          'result', session_question.result,
          'presentedAt', session_question.presented_at,
          'deadlineAt', session_question.deadline_at,
          'submittedAt', session_question.submitted_at,
          'revealAt', session_question.reveal_at,
          'resolvedAt', session_question.resolved_at,
          'responseTimeMs', session_question.response_time_ms
        )
        order by session_question.question_order
      ),
      '[]'::jsonb
    )
    into history_items
    from public.game_session_questions as session_question
    join public.game_session_answer_keys as answer_key
      on answer_key.session_question_id = session_question.id
    where session_question.session_id = selected_history.game_session_id;
  end if;

  return jsonb_build_object(
    'historyId', selected_history.id,
    'gameSessionId', selected_history.game_session_id,
    'sessionType', selected_history.session_type,
    'items', history_items
  );
end;
$$;

revoke all on function public.sync_activity_history_session(uuid)
  from public, anon, authenticated;
revoke all on function public.sync_activity_history()
  from public, anon, authenticated;
revoke all on function public.get_activity_history_details(bigint)
  from public, anon, authenticated;
grant execute on function public.get_activity_history_details(bigint)
  to authenticated;

commit;
