begin;

alter table public.users
  add column if not exists account_setup_completed_at timestamptz;

update public.users
set account_setup_completed_at = now()
where status = 'active'
  and account_setup_completed_at is null;

do $$
declare
  payment_id_type text;
  incoming_foreign_keys text;
  next_payment_id bigint;
begin
  select format_type(attribute.atttypid, attribute.atttypmod)
    into payment_id_type
  from pg_attribute as attribute
  where attribute.attrelid = 'public.payments'::regclass
    and attribute.attname = 'id'
    and not attribute.attisdropped;

  if payment_id_type = 'uuid' then
    select string_agg(
      format(
        '%I.%I (%I)',
        namespace.nspname,
        relation.relname,
        constraint_record.conname
      ),
      ', '
    )
      into incoming_foreign_keys
    from pg_constraint as constraint_record
    join pg_class as relation
      on relation.oid = constraint_record.conrelid
    join pg_namespace as namespace
      on namespace.oid = relation.relnamespace
    where constraint_record.contype = 'f'
      and constraint_record.confrelid = 'public.payments'::regclass
      and (
        select attribute.attnum
        from pg_attribute as attribute
        where attribute.attrelid = 'public.payments'::regclass
          and attribute.attname = 'id'
          and not attribute.attisdropped
      ) = any (constraint_record.confkey);

    if incoming_foreign_keys is not null then
      raise exception
        'Cannot convert public.payments.id while referenced by: %',
        incoming_foreign_keys;
    end if;

    create temporary sequence payments_id_uuid_to_bigint_sequence start with 1;

    alter table public.payments alter column id drop default;
    alter table public.payments
      alter column id type bigint
      using nextval('pg_temp.payments_id_uuid_to_bigint_sequence'::regclass);
    alter table public.payments
      alter column id add generated by default as identity;

    select coalesce(max(id), 0) + 1
      into next_payment_id
    from public.payments;

    execute format(
      'alter table public.payments alter column id restart with %s',
      next_payment_id
    );

    drop sequence pg_temp.payments_id_uuid_to_bigint_sequence;
  elsif payment_id_type = 'bigint' then
    null;
  else
    raise exception
      'Expected public.payments.id to be uuid or bigint, found %',
      payment_id_type;
  end if;
end
$$;

commit;
