begin;

create table if not exists public.game_sessions (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.users(user_id) on delete cascade,
  area_id bigint references public.subject_areas(id) on delete set null,
  area_name text not null,
  game_type text not null,
  difficulty text not null,
  timer_seconds smallint not null,
  total_questions integer not null default 0,
  current_question_order integer not null default 0,
  status text not null default 'ready',
  end_reason text,
  prepared_at timestamptz not null default now(),
  started_at timestamptz,
  ended_at timestamptz,
  constraint game_sessions_game_type_check check (
    game_type in ('Guess the Word', 'AB-Solution', 'Situationship')
  ),
  constraint game_sessions_difficulty_check check (
    difficulty in ('Easy', 'Medium', 'Hard')
  ),
  constraint game_sessions_timer_seconds_check check (timer_seconds > 0),
  constraint game_sessions_total_questions_check check (total_questions >= 0),
  constraint game_sessions_current_question_order_check check (
    current_question_order >= 0
  ),
  constraint game_sessions_status_check check (
    status in ('ready', 'in_progress', 'completed', 'exited', 'cancelled')
  ),
  constraint game_sessions_end_reason_check check (
    end_reason is null
    or end_reason in ('completed', 'user_exit', 'countdown_cancelled')
  )
);

create table if not exists public.game_session_questions (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.game_sessions(id) on delete cascade,
  question_id bigint references public.questions(id) on delete set null,
  question_set_id bigint references public.question_sets(id) on delete set null,
  subject_id bigint references public.subjects(id) on delete set null,
  subject_name text not null,
  question_text text not null,
  options jsonb not null,
  question_order integer not null,
  status text not null default 'pending',
  result text,
  selected_option_id bigint,
  presented_at timestamptz,
  deadline_at timestamptz,
  submitted_at timestamptz,
  reveal_at timestamptz,
  resolved_at timestamptz,
  response_time_ms integer,
  constraint game_session_questions_order_check check (question_order > 0),
  constraint game_session_questions_options_check check (
    jsonb_typeof(options) = 'array'
    and jsonb_array_length(options) = 4
  ),
  constraint game_session_questions_status_check check (
    status in (
      'pending',
      'active',
      'submitted',
      'answered',
      'timed_out',
      'abandoned',
      'not_played',
      'cancelled'
    )
  ),
  constraint game_session_questions_result_check check (
    result is null or result in ('correct', 'incorrect', 'unanswered')
  ),
  constraint game_session_questions_response_time_check check (
    response_time_ms is null or response_time_ms >= 0
  ),
  constraint game_session_questions_session_order_key unique (
    session_id,
    question_order
  )
);

create table if not exists public.game_session_answer_keys (
  session_question_id bigint primary key
    references public.game_session_questions(id) on delete cascade,
  correct_option_id bigint not null
);

create index if not exists game_sessions_user_prepared_at_idx
  on public.game_sessions(user_id, prepared_at desc);

create index if not exists game_session_questions_session_status_idx
  on public.game_session_questions(session_id, status);

alter table public.game_sessions enable row level security;
alter table public.game_session_questions enable row level security;
alter table public.game_session_answer_keys enable row level security;

drop policy if exists "Reviewees can view their game sessions"
  on public.game_sessions;
create policy "Reviewees can view their game sessions"
on public.game_sessions
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Reviewees can view their game session questions"
  on public.game_session_questions;
create policy "Reviewees can view their game session questions"
on public.game_session_questions
for select
to authenticated
using (
  exists (
    select 1
    from public.game_sessions
    where game_sessions.id = game_session_questions.session_id
      and game_sessions.user_id = (select auth.uid())
  )
);

revoke all on table public.game_sessions from public, anon, authenticated;
revoke all on table public.game_session_questions from public, anon, authenticated;
revoke all on table public.game_session_answer_keys from public, anon, authenticated;
grant select on table public.game_sessions to authenticated;
grant select on table public.game_session_questions to authenticated;

create or replace function public.quiz_reviewee_user_id()
returns uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
begin
  authenticated_user_id := auth.uid();

  if authenticated_user_id is null then
    raise exception 'You must be logged in to play a quiz'
      using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.user_roles
    join public.roles on roles.id = user_roles.role_id
    where user_roles.user_id = authenticated_user_id
      and roles.name = 'reviewee'
  ) then
    raise exception 'You are not authorized to play a quiz'
      using errcode = '42501';
  end if;

  return authenticated_user_id;
end;
$$;

create or replace function public.quiz_timer_seconds(
  selected_game_type text,
  selected_difficulty text
)
returns smallint
language plpgsql
immutable
set search_path = ''
as $$
begin
  if selected_game_type = 'Guess the Word' then
    return case selected_difficulty
      when 'Easy' then 10
      when 'Medium' then 15
      when 'Hard' then 20
      else null
    end;
  end if;

  if selected_game_type in ('AB-Solution', 'Situationship') then
    return case selected_difficulty
      when 'Easy' then 20
      when 'Medium' then 30
      when 'Hard' then 60
      else null
    end;
  end if;

  return null;
end;
$$;

create or replace function public.quiz_session_summary(
  selected_session_id uuid,
  authenticated_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_session public.game_sessions%rowtype;
  correct_count integer;
  incorrect_count integer;
  timed_out_count integer;
  not_played_count integer;
  questions_reached_count integer;
  answered_count integer;
  completed_question_count integer;
  accuracy_percentage numeric;
  completion_percentage numeric;
  duration_seconds integer;
begin
  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id;

  if not found then
    raise exception 'Quiz session was not found'
      using errcode = 'P0002';
  end if;

  select
    count(*) filter (where result = 'correct'),
    count(*) filter (where result = 'incorrect'),
    count(*) filter (where status = 'timed_out'),
    count(*) filter (where status in ('abandoned', 'not_played')),
    count(*) filter (
      where status in (
        'active',
        'submitted',
        'answered',
        'timed_out',
        'abandoned'
      )
    )
  into
    correct_count,
    incorrect_count,
    timed_out_count,
    not_played_count,
    questions_reached_count
  from public.game_session_questions
  where session_id = selected_session_id;

  answered_count := correct_count + incorrect_count;
  completed_question_count := answered_count + timed_out_count;

  accuracy_percentage := case
    when answered_count = 0 then 0
    else round((correct_count::numeric / answered_count::numeric) * 100, 2)
  end;

  completion_percentage := case
    when selected_session.total_questions = 0 then 0
    else round(
      (
        completed_question_count::numeric
        / selected_session.total_questions::numeric
      ) * 100,
      2
    )
  end;

  duration_seconds := case
    when selected_session.started_at is null then 0
    else greatest(
      0,
      floor(
        extract(
          epoch from (
            coalesce(selected_session.ended_at, clock_timestamp())
            - selected_session.started_at
          )
        )
      )::integer
    )
  end;

  return jsonb_build_object(
    'sessionId', selected_session.id,
    'status', selected_session.status,
    'endReason', selected_session.end_reason,
    'areaId', selected_session.area_id,
    'areaName', selected_session.area_name,
    'gameType', selected_session.game_type,
    'difficulty', selected_session.difficulty,
    'totalQuestions', selected_session.total_questions,
    'correct', correct_count,
    'incorrect', incorrect_count,
    'timedOut', timed_out_count,
    'notPlayed', not_played_count,
    'questionsReached', questions_reached_count,
    'answered', answered_count,
    'accuracyPercentage', accuracy_percentage,
    'completionPercentage', completion_percentage,
    'durationSeconds', duration_seconds
  );
end;
$$;

create or replace function public.prepare_quiz_session(
  selected_area_id bigint,
  selected_game_type text,
  selected_difficulty text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_area_name text;
  selected_timer_seconds smallint;
  created_session_id uuid;
  created_session_question_id bigint;
  question_number integer := 0;
  selected_question record;
  prepared_questions jsonb;
begin
  authenticated_user_id := public.quiz_reviewee_user_id();
  selected_timer_seconds := public.quiz_timer_seconds(
    selected_game_type,
    selected_difficulty
  );

  if selected_timer_seconds is null then
    raise exception 'A valid game type and difficulty are required'
      using errcode = '22023';
  end if;

  select subject_areas.name
  into selected_area_name
  from public.subject_areas
  where subject_areas.id = selected_area_id;

  if not found then
    raise exception 'A valid subject area is required'
      using errcode = '22023';
  end if;

  insert into public.game_sessions (
    user_id,
    area_id,
    area_name,
    game_type,
    difficulty,
    timer_seconds
  )
  values (
    authenticated_user_id,
    selected_area_id,
    selected_area_name,
    selected_game_type,
    selected_difficulty,
    selected_timer_seconds
  )
  returning id into created_session_id;

  for selected_question in
    select
      questions.id as question_id,
      questions.question_set_id,
      question_sets.subject_id,
      subjects.name as subject_name,
      questions.question_text,
      jsonb_agg(
        jsonb_build_object(
          'id', question_options.id,
          'text', question_options.option_text,
          'sortOrder', question_options.sort_order
        )
        order by question_options.sort_order
      ) as options,
      max(question_options.id) filter (
        where question_options.is_correct
      ) as correct_option_id
    from public.questions
    join public.question_sets
      on question_sets.id = questions.question_set_id
    join public.subjects
      on subjects.id = question_sets.subject_id
    join public.question_options
      on question_options.question_id = questions.id
    where subjects.area_id = selected_area_id
      and question_sets.game_type = selected_game_type
      and question_sets.difficulty = selected_difficulty
    group by
      questions.id,
      questions.question_set_id,
      question_sets.subject_id,
      subjects.name,
      questions.question_text
    having count(question_options.id) = 4
      and count(question_options.id) filter (
        where question_options.is_correct
      ) = 1
    order by random()
  loop
    question_number := question_number + 1;

    insert into public.game_session_questions (
      session_id,
      question_id,
      question_set_id,
      subject_id,
      subject_name,
      question_text,
      options,
      question_order
    )
    values (
      created_session_id,
      selected_question.question_id,
      selected_question.question_set_id,
      selected_question.subject_id,
      selected_question.subject_name,
      selected_question.question_text,
      selected_question.options,
      question_number
    )
    returning id into created_session_question_id;

    insert into public.game_session_answer_keys (
      session_question_id,
      correct_option_id
    )
    values (
      created_session_question_id,
      selected_question.correct_option_id
    );
  end loop;

  if question_number = 0 then
    delete from public.game_sessions
    where id = created_session_id;

    return jsonb_build_object('status', 'empty');
  end if;

  update public.game_sessions
  set total_questions = question_number
  where id = created_session_id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'sessionQuestionId', game_session_questions.id,
        'questionOrder', game_session_questions.question_order,
        'subjectName', game_session_questions.subject_name,
        'questionText', game_session_questions.question_text,
        'options', game_session_questions.options
      )
      order by game_session_questions.question_order
    ),
    '[]'::jsonb
  )
  into prepared_questions
  from public.game_session_questions
  where game_session_questions.session_id = created_session_id;

  return jsonb_build_object(
    'status', 'prepared',
    'sessionId', created_session_id,
    'areaId', selected_area_id,
    'areaName', selected_area_name,
    'gameType', selected_game_type,
    'difficulty', selected_difficulty,
    'timerSeconds', selected_timer_seconds,
    'totalQuestions', question_number,
    'questions', prepared_questions
  );
end;
$$;

create or replace function public.start_quiz_session(
  selected_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  first_question public.game_session_questions%rowtype;
  started_time timestamptz;
  question_deadline timestamptz;
begin
  authenticated_user_id := public.quiz_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
  for update;

  if not found then
    raise exception 'Quiz session was not found'
      using errcode = 'P0002';
  end if;

  if selected_session.status <> 'ready' then
    raise exception 'Quiz session cannot be started'
      using errcode = '55000';
  end if;

  select game_session_questions.*
  into first_question
  from public.game_session_questions
  where game_session_questions.session_id = selected_session_id
    and game_session_questions.question_order = 1
  for update;

  if not found then
    raise exception 'Quiz session does not contain questions'
      using errcode = '55000';
  end if;

  started_time := clock_timestamp();
  question_deadline := started_time
    + make_interval(secs => selected_session.timer_seconds);

  update public.game_sessions
  set
    status = 'in_progress',
    current_question_order = 1,
    started_at = started_time
  where id = selected_session_id;

  update public.game_session_questions
  set
    status = 'active',
    presented_at = started_time,
    deadline_at = question_deadline
  where id = first_question.id;

  return jsonb_build_object(
    'sessionId', selected_session_id,
    'sessionQuestionId', first_question.id,
    'questionOrder', 1,
    'status', 'active',
    'serverNow', started_time,
    'deadlineAt', question_deadline
  );
end;
$$;

create or replace function public.submit_quiz_answer(
  selected_session_question_id bigint,
  selected_option_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  selected_question public.game_session_questions%rowtype;
  submitted_time timestamptz;
  answer_reveal_time timestamptz;
begin
  authenticated_user_id := public.quiz_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  join public.game_session_questions
    on game_session_questions.session_id = game_sessions.id
  where game_session_questions.id = selected_session_question_id
    and game_sessions.user_id = authenticated_user_id
  for update of game_sessions;

  if not found then
    raise exception 'Quiz question was not found'
      using errcode = 'P0002';
  end if;

  select game_session_questions.*
  into selected_question
  from public.game_session_questions
  where game_session_questions.id = selected_session_question_id
  for update;

  if selected_session.status <> 'in_progress'
    or selected_session.current_question_order <> selected_question.question_order
    or selected_question.status <> 'active'
  then
    raise exception 'Quiz question is not accepting answers'
      using errcode = '55000';
  end if;

  submitted_time := clock_timestamp();

  if selected_question.deadline_at is null
    or submitted_time > selected_question.deadline_at
  then
    raise exception 'The answer deadline has passed'
      using errcode = '57014';
  end if;

  if not exists (
    select 1
    from jsonb_array_elements(selected_question.options) as quiz_option
    where (quiz_option->>'id')::bigint = selected_option_id
  ) then
    raise exception 'The selected answer is invalid'
      using errcode = '22023';
  end if;

  answer_reveal_time := submitted_time + interval '3 seconds';

  update public.game_session_questions
  set
    status = 'submitted',
    selected_option_id = $2,
    submitted_at = submitted_time,
    reveal_at = answer_reveal_time,
    response_time_ms = greatest(
      0,
      floor(
        extract(epoch from (submitted_time - selected_question.presented_at))
        * 1000
      )::integer
    )
  where id = selected_session_question_id;

  return jsonb_build_object(
    'sessionQuestionId', selected_session_question_id,
    'status', 'submitted',
    'submittedAt', submitted_time,
    'revealAt', answer_reveal_time
  );
end;
$$;

create or replace function public.reveal_quiz_answer(
  selected_session_question_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_question public.game_session_questions%rowtype;
  correct_option_id bigint;
  answer_is_correct boolean;
  answer_result text;
  resolved_time timestamptz;
begin
  authenticated_user_id := public.quiz_reviewee_user_id();

  select game_session_questions.*
  into selected_question
  from public.game_session_questions
  join public.game_sessions
    on game_sessions.id = game_session_questions.session_id
  where game_session_questions.id = selected_session_question_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.status = 'in_progress'
  for update of game_session_questions;

  if not found then
    raise exception 'Quiz question was not found'
      using errcode = 'P0002';
  end if;

  if selected_question.status <> 'submitted'
    or selected_question.selected_option_id is null
    or selected_question.reveal_at is null
  then
    raise exception 'Quiz answer is not ready to be revealed'
      using errcode = '55000';
  end if;

  resolved_time := clock_timestamp();

  if resolved_time < selected_question.reveal_at then
    raise exception 'Quiz answer cannot be revealed yet'
      using errcode = '55000';
  end if;

  select game_session_answer_keys.correct_option_id
  into correct_option_id
  from public.game_session_answer_keys
  where game_session_answer_keys.session_question_id =
    selected_session_question_id;

  if not found then
    raise exception 'Quiz answer key was not found'
      using errcode = 'P0002';
  end if;

  answer_is_correct := selected_question.selected_option_id =
    correct_option_id;
  answer_result := case
    when answer_is_correct then 'correct'
    else 'incorrect'
  end;

  update public.game_session_questions
  set
    status = 'answered',
    result = answer_result,
    resolved_at = resolved_time
  where id = selected_session_question_id;

  return jsonb_build_object(
    'sessionQuestionId', selected_session_question_id,
    'status', 'answered',
    'result', answer_result,
    'isCorrect', answer_is_correct,
    'correctOptionId', correct_option_id,
    'resolvedAt', resolved_time
  );
end;
$$;

create or replace function public.timeout_quiz_question(
  selected_session_question_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  selected_question public.game_session_questions%rowtype;
  resolved_time timestamptz;
begin
  authenticated_user_id := public.quiz_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  join public.game_session_questions
    on game_session_questions.session_id = game_sessions.id
  where game_session_questions.id = selected_session_question_id
    and game_sessions.user_id = authenticated_user_id
  for update of game_sessions;

  if not found then
    raise exception 'Quiz question was not found'
      using errcode = 'P0002';
  end if;

  select game_session_questions.*
  into selected_question
  from public.game_session_questions
  where game_session_questions.id = selected_session_question_id
  for update;

  if selected_session.status <> 'in_progress'
    or selected_session.current_question_order <> selected_question.question_order
    or selected_question.status <> 'active'
  then
    raise exception 'Quiz question cannot be timed out'
      using errcode = '55000';
  end if;

  resolved_time := clock_timestamp();

  if selected_question.deadline_at is null
    or resolved_time < selected_question.deadline_at
  then
    raise exception 'Quiz question has not reached its deadline'
      using errcode = '55000';
  end if;

  update public.game_session_questions
  set
    status = 'timed_out',
    result = 'unanswered',
    resolved_at = resolved_time
  where id = selected_session_question_id;

  return jsonb_build_object(
    'sessionQuestionId', selected_session_question_id,
    'status', 'timed_out',
    'result', 'unanswered',
    'resolvedAt', resolved_time
  );
end;
$$;

create or replace function public.advance_quiz_session(
  selected_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  current_question public.game_session_questions%rowtype;
  next_question public.game_session_questions%rowtype;
  activated_time timestamptz;
  question_deadline timestamptz;
begin
  authenticated_user_id := public.quiz_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
  for update;

  if not found then
    raise exception 'Quiz session was not found'
      using errcode = 'P0002';
  end if;

  if selected_session.status <> 'in_progress' then
    raise exception 'Quiz session cannot be advanced'
      using errcode = '55000';
  end if;

  select game_session_questions.*
  into current_question
  from public.game_session_questions
  where game_session_questions.session_id = selected_session_id
    and game_session_questions.question_order =
      selected_session.current_question_order
  for update;

  if not found then
    raise exception 'The current quiz question was not found'
      using errcode = 'P0002';
  end if;

  if current_question.status not in ('answered', 'timed_out') then
    raise exception 'The current quiz question is not finished'
      using errcode = '55000';
  end if;

  if selected_session.current_question_order >=
    selected_session.total_questions
  then
    update public.game_sessions
    set
      status = 'completed',
      end_reason = 'completed',
      ended_at = clock_timestamp()
    where id = selected_session_id;

    return jsonb_build_object(
      'completed', true,
      'timing', null,
      'summary', public.quiz_session_summary(
        selected_session_id,
        authenticated_user_id
      )
    );
  end if;

  select game_session_questions.*
  into next_question
  from public.game_session_questions
  where game_session_questions.session_id = selected_session_id
    and game_session_questions.question_order =
      selected_session.current_question_order + 1
    and game_session_questions.status = 'pending'
  for update;

  if not found then
    raise exception 'The next quiz question was not found'
      using errcode = 'P0002';
  end if;

  activated_time := clock_timestamp();
  question_deadline := activated_time
    + make_interval(secs => selected_session.timer_seconds);

  update public.game_session_questions
  set
    status = 'active',
    presented_at = activated_time,
    deadline_at = question_deadline
  where id = next_question.id;

  update public.game_sessions
  set current_question_order = next_question.question_order
  where id = selected_session_id;

  return jsonb_build_object(
    'completed', false,
    'timing', jsonb_build_object(
      'sessionId', selected_session_id,
      'sessionQuestionId', next_question.id,
      'questionOrder', next_question.question_order,
      'status', 'active',
      'serverNow', activated_time,
      'deadlineAt', question_deadline
    ),
    'summary', null
  );
end;
$$;

create or replace function public.cancel_quiz_session(
  selected_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  cancelled_time timestamptz;
begin
  authenticated_user_id := public.quiz_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
  for update;

  if not found then
    raise exception 'Quiz session was not found'
      using errcode = 'P0002';
  end if;

  if selected_session.status <> 'ready' then
    raise exception 'Quiz session cannot be cancelled'
      using errcode = '55000';
  end if;

  cancelled_time := clock_timestamp();

  update public.game_session_questions
  set
    status = 'cancelled',
    result = 'unanswered',
    resolved_at = cancelled_time
  where session_id = selected_session_id
    and status = 'pending';

  update public.game_sessions
  set
    status = 'cancelled',
    end_reason = 'countdown_cancelled',
    ended_at = cancelled_time
  where id = selected_session_id;

  return jsonb_build_object(
    'sessionId', selected_session_id,
    'status', 'cancelled'
  );
end;
$$;

create or replace function public.exit_quiz_session(
  selected_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  current_question public.game_session_questions%rowtype;
  correct_option_id bigint;
  answer_result text;
  exited_time timestamptz;
begin
  authenticated_user_id := public.quiz_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
  for update;

  if not found then
    raise exception 'Quiz session was not found'
      using errcode = 'P0002';
  end if;

  if selected_session.status in ('completed', 'exited') then
    return public.quiz_session_summary(
      selected_session_id,
      authenticated_user_id
    );
  end if;

  if selected_session.status <> 'in_progress' then
    raise exception 'Quiz session cannot be exited'
      using errcode = '55000';
  end if;

  exited_time := clock_timestamp();

  select game_session_questions.*
  into current_question
  from public.game_session_questions
  where game_session_questions.session_id = selected_session_id
    and game_session_questions.question_order =
      selected_session.current_question_order
  for update;

  if current_question.status = 'active' then
    update public.game_session_questions
    set
      status = 'abandoned',
      result = 'unanswered',
      resolved_at = exited_time
    where id = current_question.id;
  elsif current_question.status = 'submitted' then
    select game_session_answer_keys.correct_option_id
    into correct_option_id
    from public.game_session_answer_keys
    where game_session_answer_keys.session_question_id =
      current_question.id;

    answer_result := case
      when current_question.selected_option_id = correct_option_id
        then 'correct'
      else 'incorrect'
    end;

    update public.game_session_questions
    set
      status = 'answered',
      result = answer_result,
      resolved_at = exited_time
    where id = current_question.id;
  end if;

  update public.game_session_questions
  set
    status = 'not_played',
    result = 'unanswered',
    resolved_at = exited_time
  where session_id = selected_session_id
    and status = 'pending';

  update public.game_sessions
  set
    status = 'exited',
    end_reason = 'user_exit',
    ended_at = exited_time
  where id = selected_session_id;

  return public.quiz_session_summary(
    selected_session_id,
    authenticated_user_id
  );
end;
$$;

revoke all on function public.quiz_reviewee_user_id() from public, anon, authenticated;
revoke all on function public.quiz_timer_seconds(text, text) from public, anon, authenticated;
revoke all on function public.quiz_session_summary(uuid, uuid) from public, anon, authenticated;

revoke all on function public.prepare_quiz_session(bigint, text, text)
  from public, anon;
revoke all on function public.start_quiz_session(uuid)
  from public, anon;
revoke all on function public.submit_quiz_answer(bigint, bigint)
  from public, anon;
revoke all on function public.reveal_quiz_answer(bigint)
  from public, anon;
revoke all on function public.timeout_quiz_question(bigint)
  from public, anon;
revoke all on function public.advance_quiz_session(uuid)
  from public, anon;
revoke all on function public.cancel_quiz_session(uuid)
  from public, anon;
revoke all on function public.exit_quiz_session(uuid)
  from public, anon;

grant execute on function public.prepare_quiz_session(bigint, text, text)
  to authenticated;
grant execute on function public.start_quiz_session(uuid)
  to authenticated;
grant execute on function public.submit_quiz_answer(bigint, bigint)
  to authenticated;
grant execute on function public.reveal_quiz_answer(bigint)
  to authenticated;
grant execute on function public.timeout_quiz_question(bigint)
  to authenticated;
grant execute on function public.advance_quiz_session(uuid)
  to authenticated;
grant execute on function public.cancel_quiz_session(uuid)
  to authenticated;
grant execute on function public.exit_quiz_session(uuid)
  to authenticated;

commit;
