begin;

alter table public.game_sessions
  add column if not exists session_type text not null default 'mcq_quiz';

alter table public.game_sessions
  add column if not exists flash_card_deck_id bigint;

update public.game_sessions
set session_type = 'mcq_quiz'
where session_type is null;

alter table public.game_sessions
  alter column session_type set default 'mcq_quiz',
  alter column session_type set not null,
  alter column difficulty drop not null;

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conname = 'game_sessions_flash_card_deck_id_fkey'
      and conrelid = 'public.game_sessions'::regclass
  ) then
    alter table public.game_sessions
      add constraint game_sessions_flash_card_deck_id_fkey
      foreign key (flash_card_deck_id)
      references public.flash_card_decks(id)
      on delete set null;
  end if;
end;
$$;

alter table public.game_sessions
  drop constraint if exists game_sessions_session_type_check,
  drop constraint if exists game_sessions_game_type_check,
  drop constraint if exists game_sessions_difficulty_check,
  drop constraint if exists game_sessions_flash_card_fields_check,
  drop constraint if exists game_sessions_flash_card_timer_check;

alter table public.game_sessions
  add constraint game_sessions_session_type_check check (
    session_type in ('mcq_quiz', 'flash_cards')
  ),
  add constraint game_sessions_game_type_check check (
    (
      session_type = 'mcq_quiz'
      and game_type in (
        'Guess the Word',
        'AB-Solution',
        'Situationship'
      )
    )
    or (
      session_type = 'flash_cards'
      and game_type = 'Flash Cards'
    )
  ),
  add constraint game_sessions_difficulty_check check (
    (
      session_type = 'mcq_quiz'
      and difficulty is not null
      and difficulty in ('Easy', 'Medium', 'Hard')
    )
    or (
      session_type = 'flash_cards'
      and difficulty is null
    )
  ),
  add constraint game_sessions_flash_card_fields_check check (
    session_type = 'flash_cards'
    or flash_card_deck_id is null
  ),
  add constraint game_sessions_flash_card_timer_check check (
    session_type <> 'flash_cards'
    or timer_seconds = 10
  );

create table if not exists public.game_session_flash_cards (
  id bigint generated by default as identity primary key,
  session_id uuid not null
    references public.game_sessions(id) on delete cascade,
  flash_card_id bigint
    references public.flash_cards(id) on delete set null,
  question_text text not null,
  submitted_answer text,
  card_order integer not null,
  status text not null default 'pending',
  result text,
  presented_at timestamptz,
  deadline_at timestamptz,
  submitted_at timestamptz,
  reveal_at timestamptz,
  resolved_at timestamptz,
  response_time_ms integer,
  constraint game_session_flash_cards_question_check check (
    char_length(btrim(question_text)) between 1 and 1000
  ),
  constraint game_session_flash_cards_answer_check check (
    submitted_answer is null
    or char_length(btrim(submitted_answer)) between 1 and 2000
  ),
  constraint game_session_flash_cards_order_check check (card_order > 0),
  constraint game_session_flash_cards_status_check check (
    status in (
      'pending',
      'active',
      'submitted',
      'answered',
      'timed_out',
      'abandoned',
      'not_played',
      'cancelled'
    )
  ),
  constraint game_session_flash_cards_result_check check (
    result is null or result in ('correct', 'incorrect', 'unanswered')
  ),
  constraint game_session_flash_cards_response_time_check check (
    response_time_ms is null or response_time_ms >= 0
  ),
  constraint game_session_flash_cards_session_order_key unique (
    session_id,
    card_order
  )
);

create table if not exists public.game_session_flash_card_answer_keys (
  session_flash_card_id bigint primary key
    references public.game_session_flash_cards(id) on delete cascade,
  correct_answer text not null,
  constraint game_session_flash_card_answer_keys_answer_check check (
    char_length(btrim(correct_answer)) between 1 and 2000
  )
);

create index if not exists game_sessions_user_history_idx
  on public.game_sessions(user_id, ended_at desc)
  where status in ('completed', 'exited');

create index if not exists game_sessions_flash_card_deck_id_idx
  on public.game_sessions(flash_card_deck_id)
  where flash_card_deck_id is not null;

create index if not exists game_session_flash_cards_session_status_idx
  on public.game_session_flash_cards(session_id, status);

create index if not exists game_session_flash_cards_flash_card_id_idx
  on public.game_session_flash_cards(flash_card_id)
  where flash_card_id is not null;

alter table public.game_session_flash_cards enable row level security;
alter table public.game_session_flash_card_answer_keys enable row level security;

drop policy if exists "Reviewees can view their game session flash cards"
  on public.game_session_flash_cards;
create policy "Reviewees can view their game session flash cards"
on public.game_session_flash_cards
for select
to authenticated
using (
  exists (
    select 1
    from public.game_sessions
    where game_sessions.id = game_session_flash_cards.session_id
      and game_sessions.user_id = (select auth.uid())
      and game_sessions.session_type = 'flash_cards'
  )
);

revoke all on table public.game_session_flash_cards
  from public, anon, authenticated;
revoke all on table public.game_session_flash_card_answer_keys
  from public, anon, authenticated;
grant select on table public.game_session_flash_cards to authenticated;
grant all on table public.game_session_flash_cards to service_role;
grant all on table public.game_session_flash_card_answer_keys to service_role;

revoke all on sequence public.game_session_flash_cards_id_seq
  from public, anon, authenticated;
grant all on sequence public.game_session_flash_cards_id_seq to service_role;

create or replace function public.flash_card_reviewee_user_id()
returns uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
begin
  authenticated_user_id := auth.uid();

  if authenticated_user_id is null then
    raise exception 'You must be logged in to play flash cards'
      using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.user_roles
    join public.roles on roles.id = user_roles.role_id
    where user_roles.user_id = authenticated_user_id
      and roles.name = 'reviewee'
  ) then
    raise exception 'You are not authorized to play flash cards'
      using errcode = '42501';
  end if;

  return authenticated_user_id;
end;
$$;

create or replace function public.normalize_flash_card_answer(
  selected_answer text
)
returns text
language sql
immutable
set search_path = ''
as $$
  select pg_catalog.lower(
    pg_catalog.regexp_replace(
      pg_catalog.btrim(selected_answer),
      '[[:space:]]+',
      ' ',
      'g'
    )
  );
$$;

create or replace function public.flash_card_session_summary(
  selected_session_id uuid,
  authenticated_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_session public.game_sessions%rowtype;
  correct_count integer;
  incorrect_count integer;
  timed_out_count integer;
  not_played_count integer;
  questions_reached_count integer;
  answered_count integer;
  completed_question_count integer;
  accuracy_percentage numeric;
  completion_percentage numeric;
  duration_seconds integer;
begin
  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.session_type = 'flash_cards';

  if not found then
    raise exception 'Flash card session was not found'
      using errcode = 'P0002';
  end if;

  select
    count(*) filter (where result = 'correct'),
    count(*) filter (where result = 'incorrect'),
    count(*) filter (where status = 'timed_out'),
    count(*) filter (where status in ('abandoned', 'not_played')),
    count(*) filter (
      where status in (
        'active',
        'submitted',
        'answered',
        'timed_out',
        'abandoned'
      )
    )
  into
    correct_count,
    incorrect_count,
    timed_out_count,
    not_played_count,
    questions_reached_count
  from public.game_session_flash_cards
  where session_id = selected_session_id;

  answered_count := correct_count + incorrect_count;
  completed_question_count := answered_count + timed_out_count;

  accuracy_percentage := case
    when answered_count = 0 then 0
    else round((correct_count::numeric / answered_count::numeric) * 100, 2)
  end;

  completion_percentage := case
    when selected_session.total_questions = 0 then 0
    else round(
      (
        completed_question_count::numeric
        / selected_session.total_questions::numeric
      ) * 100,
      2
    )
  end;

  duration_seconds := case
    when selected_session.started_at is null then 0
    else greatest(
      0,
      floor(
        extract(
          epoch from (
            coalesce(selected_session.ended_at, clock_timestamp())
            - selected_session.started_at
          )
        )
      )::integer
    )
  end;

  return jsonb_build_object(
    'sessionId', selected_session.id,
    'status', selected_session.status,
    'endReason', selected_session.end_reason,
    'areaId', selected_session.area_id,
    'areaName', selected_session.area_name,
    'gameType', selected_session.game_type,
    'difficulty', selected_session.difficulty,
    'totalQuestions', selected_session.total_questions,
    'correct', correct_count,
    'incorrect', incorrect_count,
    'timedOut', timed_out_count,
    'notPlayed', not_played_count,
    'questionsReached', questions_reached_count,
    'answered', answered_count,
    'accuracyPercentage', accuracy_percentage,
    'completionPercentage', completion_percentage,
    'durationSeconds', duration_seconds
  );
end;
$$;

create or replace function public.prepare_flash_card_session(
  selected_area_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_deck public.flash_card_decks%rowtype;
  selected_area_name text;
  created_session_id uuid;
  created_session_flash_card_id bigint;
  flash_card_number integer := 0;
  selected_flash_card record;
  prepared_flash_cards jsonb;
  selected_timer_seconds constant smallint := 10;
begin
  authenticated_user_id := public.flash_card_reviewee_user_id();

  select flash_card_decks.*
  into selected_deck
  from public.flash_card_decks
  where flash_card_decks.user_id = authenticated_user_id
    and flash_card_decks.area_id = selected_area_id;

  if not found then
    return jsonb_build_object('status', 'empty');
  end if;

  select subject_areas.name
  into selected_area_name
  from public.subject_areas
  where subject_areas.id = selected_area_id;

  if not found then
    raise exception 'A valid subject area is required'
      using errcode = '22023';
  end if;

  insert into public.game_sessions (
    user_id,
    area_id,
    area_name,
    session_type,
    flash_card_deck_id,
    game_type,
    difficulty,
    timer_seconds
  )
  values (
    authenticated_user_id,
    selected_area_id,
    selected_area_name,
    'flash_cards',
    selected_deck.id,
    'Flash Cards',
    null,
    selected_timer_seconds
  )
  returning id into created_session_id;

  for selected_flash_card in
    select
      flash_cards.id,
      flash_cards.question,
      flash_cards.answer
    from public.flash_cards
    where flash_cards.deck_id = selected_deck.id
    order by random()
  loop
    flash_card_number := flash_card_number + 1;

    insert into public.game_session_flash_cards (
      session_id,
      flash_card_id,
      question_text,
      card_order
    )
    values (
      created_session_id,
      selected_flash_card.id,
      selected_flash_card.question,
      flash_card_number
    )
    returning id into created_session_flash_card_id;

    insert into public.game_session_flash_card_answer_keys (
      session_flash_card_id,
      correct_answer
    )
    values (
      created_session_flash_card_id,
      selected_flash_card.answer
    );
  end loop;

  if flash_card_number = 0 then
    delete from public.game_sessions
    where id = created_session_id;

    return jsonb_build_object('status', 'empty');
  end if;

  update public.game_sessions
  set total_questions = flash_card_number
  where id = created_session_id;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'sessionFlashCardId', game_session_flash_cards.id,
        'cardOrder', game_session_flash_cards.card_order,
        'questionText', game_session_flash_cards.question_text
      )
      order by game_session_flash_cards.card_order
    ),
    '[]'::jsonb
  )
  into prepared_flash_cards
  from public.game_session_flash_cards
  where game_session_flash_cards.session_id = created_session_id;

  return jsonb_build_object(
    'status', 'prepared',
    'sessionId', created_session_id,
    'areaId', selected_area_id,
    'areaName', selected_area_name,
    'timerSeconds', selected_timer_seconds,
    'totalFlashCards', flash_card_number,
    'flashCards', prepared_flash_cards
  );
end;
$$;

create or replace function public.start_flash_card_session(
  selected_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  first_flash_card public.game_session_flash_cards%rowtype;
  started_time timestamptz;
  flash_card_deadline timestamptz;
begin
  authenticated_user_id := public.flash_card_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.session_type = 'flash_cards'
  for update;

  if not found then
    raise exception 'Flash card session was not found'
      using errcode = 'P0002';
  end if;

  if selected_session.status <> 'ready' then
    raise exception 'Flash card session cannot be started'
      using errcode = '55000';
  end if;

  select game_session_flash_cards.*
  into first_flash_card
  from public.game_session_flash_cards
  where game_session_flash_cards.session_id = selected_session_id
    and game_session_flash_cards.card_order = 1
  for update;

  if not found then
    raise exception 'Flash card session does not contain cards'
      using errcode = '55000';
  end if;

  started_time := clock_timestamp();
  flash_card_deadline := started_time
    + make_interval(secs => selected_session.timer_seconds);

  update public.game_sessions
  set
    status = 'in_progress',
    current_question_order = 1,
    started_at = started_time
  where id = selected_session_id;

  update public.game_session_flash_cards
  set
    status = 'active',
    presented_at = started_time,
    deadline_at = flash_card_deadline
  where id = first_flash_card.id;

  return jsonb_build_object(
    'sessionId', selected_session_id,
    'sessionFlashCardId', first_flash_card.id,
    'cardOrder', 1,
    'status', 'active',
    'serverNow', started_time,
    'deadlineAt', flash_card_deadline
  );
end;
$$;

create or replace function public.submit_flash_card_answer(
  selected_session_flash_card_id bigint,
  selected_answer text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  selected_flash_card public.game_session_flash_cards%rowtype;
  submitted_time timestamptz;
  answer_reveal_time timestamptz;
begin
  authenticated_user_id := public.flash_card_reviewee_user_id();

  if selected_answer is null
    or char_length(btrim(selected_answer)) not between 1 and 2000
  then
    raise exception 'A valid answer is required'
      using errcode = '22023';
  end if;

  select game_sessions.*
  into selected_session
  from public.game_sessions
  join public.game_session_flash_cards
    on game_session_flash_cards.session_id = game_sessions.id
  where game_session_flash_cards.id = selected_session_flash_card_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.session_type = 'flash_cards'
  for update of game_sessions;

  if not found then
    raise exception 'Flash card was not found'
      using errcode = 'P0002';
  end if;

  select game_session_flash_cards.*
  into selected_flash_card
  from public.game_session_flash_cards
  where game_session_flash_cards.id = selected_session_flash_card_id
  for update;

  if selected_session.status <> 'in_progress'
    or selected_session.current_question_order <> selected_flash_card.card_order
    or selected_flash_card.status <> 'active'
  then
    raise exception 'Flash card is not accepting answers'
      using errcode = '55000';
  end if;

  submitted_time := clock_timestamp();

  if selected_flash_card.deadline_at is null
    or submitted_time > selected_flash_card.deadline_at
  then
    raise exception 'The answer deadline has passed'
      using errcode = '57014';
  end if;

  answer_reveal_time := submitted_time + interval '3 seconds';

  update public.game_session_flash_cards
  set
    status = 'submitted',
    submitted_answer = btrim(selected_answer),
    submitted_at = submitted_time,
    reveal_at = answer_reveal_time,
    response_time_ms = greatest(
      0,
      floor(
        extract(epoch from (submitted_time - selected_flash_card.presented_at))
        * 1000
      )::integer
    )
  where id = selected_session_flash_card_id;

  return jsonb_build_object(
    'sessionFlashCardId', selected_session_flash_card_id,
    'status', 'submitted',
    'submittedAt', submitted_time,
    'revealAt', answer_reveal_time
  );
end;
$$;

create or replace function public.reveal_flash_card_answer(
  selected_session_flash_card_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_flash_card public.game_session_flash_cards%rowtype;
  correct_answer text;
  answer_is_correct boolean;
  answer_result text;
  resolved_time timestamptz;
begin
  authenticated_user_id := public.flash_card_reviewee_user_id();

  select game_session_flash_cards.*
  into selected_flash_card
  from public.game_session_flash_cards
  join public.game_sessions
    on game_sessions.id = game_session_flash_cards.session_id
  where game_session_flash_cards.id = selected_session_flash_card_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.session_type = 'flash_cards'
    and game_sessions.status = 'in_progress'
  for update of game_session_flash_cards;

  if not found then
    raise exception 'Flash card was not found'
      using errcode = 'P0002';
  end if;

  if selected_flash_card.status <> 'submitted'
    or selected_flash_card.submitted_answer is null
    or selected_flash_card.reveal_at is null
  then
    raise exception 'Flash card answer is not ready to be revealed'
      using errcode = '55000';
  end if;

  resolved_time := clock_timestamp();

  if resolved_time < selected_flash_card.reveal_at then
    raise exception 'Flash card answer cannot be revealed yet'
      using errcode = '55000';
  end if;

  select game_session_flash_card_answer_keys.correct_answer
  into correct_answer
  from public.game_session_flash_card_answer_keys
  where game_session_flash_card_answer_keys.session_flash_card_id =
    selected_session_flash_card_id;

  if not found then
    raise exception 'Flash card answer key was not found'
      using errcode = 'P0002';
  end if;

  answer_is_correct := public.normalize_flash_card_answer(
    selected_flash_card.submitted_answer
  ) = public.normalize_flash_card_answer(correct_answer);
  answer_result := case
    when answer_is_correct then 'correct'
    else 'incorrect'
  end;

  update public.game_session_flash_cards
  set
    status = 'answered',
    result = answer_result,
    resolved_at = resolved_time
  where id = selected_session_flash_card_id;

  return jsonb_build_object(
    'sessionFlashCardId', selected_session_flash_card_id,
    'status', 'answered',
    'result', answer_result,
    'isCorrect', answer_is_correct,
    'correctAnswer', correct_answer,
    'resolvedAt', resolved_time
  );
end;
$$;

create or replace function public.timeout_flash_card(
  selected_session_flash_card_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  selected_flash_card public.game_session_flash_cards%rowtype;
  resolved_time timestamptz;
begin
  authenticated_user_id := public.flash_card_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  join public.game_session_flash_cards
    on game_session_flash_cards.session_id = game_sessions.id
  where game_session_flash_cards.id = selected_session_flash_card_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.session_type = 'flash_cards'
  for update of game_sessions;

  if not found then
    raise exception 'Flash card was not found'
      using errcode = 'P0002';
  end if;

  select game_session_flash_cards.*
  into selected_flash_card
  from public.game_session_flash_cards
  where game_session_flash_cards.id = selected_session_flash_card_id
  for update;

  if selected_session.status <> 'in_progress'
    or selected_session.current_question_order <> selected_flash_card.card_order
    or selected_flash_card.status <> 'active'
  then
    raise exception 'Flash card cannot be timed out'
      using errcode = '55000';
  end if;

  resolved_time := clock_timestamp();

  if selected_flash_card.deadline_at is null
    or resolved_time < selected_flash_card.deadline_at
  then
    raise exception 'Flash card has not reached its deadline'
      using errcode = '55000';
  end if;

  update public.game_session_flash_cards
  set
    status = 'timed_out',
    result = 'unanswered',
    resolved_at = resolved_time
  where id = selected_session_flash_card_id;

  return jsonb_build_object(
    'sessionFlashCardId', selected_session_flash_card_id,
    'status', 'timed_out',
    'result', 'unanswered',
    'resolvedAt', resolved_time
  );
end;
$$;

create or replace function public.advance_flash_card_session(
  selected_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  current_flash_card public.game_session_flash_cards%rowtype;
  next_flash_card public.game_session_flash_cards%rowtype;
  activated_time timestamptz;
  flash_card_deadline timestamptz;
begin
  authenticated_user_id := public.flash_card_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.session_type = 'flash_cards'
  for update;

  if not found then
    raise exception 'Flash card session was not found'
      using errcode = 'P0002';
  end if;

  if selected_session.status <> 'in_progress' then
    raise exception 'Flash card session cannot be advanced'
      using errcode = '55000';
  end if;

  select game_session_flash_cards.*
  into current_flash_card
  from public.game_session_flash_cards
  where game_session_flash_cards.session_id = selected_session_id
    and game_session_flash_cards.card_order =
      selected_session.current_question_order
  for update;

  if not found then
    raise exception 'The current flash card was not found'
      using errcode = 'P0002';
  end if;

  if current_flash_card.status not in ('answered', 'timed_out') then
    raise exception 'The current flash card is not finished'
      using errcode = '55000';
  end if;

  if selected_session.current_question_order >=
    selected_session.total_questions
  then
    update public.game_sessions
    set
      status = 'completed',
      end_reason = 'completed',
      ended_at = clock_timestamp()
    where id = selected_session_id;

    return jsonb_build_object(
      'completed', true,
      'timing', null,
      'summary', public.flash_card_session_summary(
        selected_session_id,
        authenticated_user_id
      )
    );
  end if;

  select game_session_flash_cards.*
  into next_flash_card
  from public.game_session_flash_cards
  where game_session_flash_cards.session_id = selected_session_id
    and game_session_flash_cards.card_order =
      selected_session.current_question_order + 1
    and game_session_flash_cards.status = 'pending'
  for update;

  if not found then
    raise exception 'The next flash card was not found'
      using errcode = 'P0002';
  end if;

  activated_time := clock_timestamp();
  flash_card_deadline := activated_time
    + make_interval(secs => selected_session.timer_seconds);

  update public.game_session_flash_cards
  set
    status = 'active',
    presented_at = activated_time,
    deadline_at = flash_card_deadline
  where id = next_flash_card.id;

  update public.game_sessions
  set current_question_order = next_flash_card.card_order
  where id = selected_session_id;

  return jsonb_build_object(
    'completed', false,
    'timing', jsonb_build_object(
      'sessionId', selected_session_id,
      'sessionFlashCardId', next_flash_card.id,
      'cardOrder', next_flash_card.card_order,
      'status', 'active',
      'serverNow', activated_time,
      'deadlineAt', flash_card_deadline
    ),
    'summary', null
  );
end;
$$;

create or replace function public.cancel_flash_card_session(
  selected_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  cancelled_time timestamptz;
begin
  authenticated_user_id := public.flash_card_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.session_type = 'flash_cards'
  for update;

  if not found then
    raise exception 'Flash card session was not found'
      using errcode = 'P0002';
  end if;

  if selected_session.status <> 'ready' then
    raise exception 'Flash card session cannot be cancelled'
      using errcode = '55000';
  end if;

  cancelled_time := clock_timestamp();

  update public.game_session_flash_cards
  set
    status = 'cancelled',
    result = 'unanswered',
    resolved_at = cancelled_time
  where session_id = selected_session_id
    and status = 'pending';

  update public.game_sessions
  set
    status = 'cancelled',
    end_reason = 'countdown_cancelled',
    ended_at = cancelled_time
  where id = selected_session_id;

  return jsonb_build_object(
    'sessionId', selected_session_id,
    'status', 'cancelled'
  );
end;
$$;

create or replace function public.exit_flash_card_session(
  selected_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  current_flash_card public.game_session_flash_cards%rowtype;
  correct_answer text;
  answer_result text;
  exited_time timestamptz;
begin
  authenticated_user_id := public.flash_card_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.session_type = 'flash_cards'
  for update;

  if not found then
    raise exception 'Flash card session was not found'
      using errcode = 'P0002';
  end if;

  if selected_session.status in ('completed', 'exited') then
    return public.flash_card_session_summary(
      selected_session_id,
      authenticated_user_id
    );
  end if;

  if selected_session.status <> 'in_progress' then
    raise exception 'Flash card session cannot be exited'
      using errcode = '55000';
  end if;

  exited_time := clock_timestamp();

  select game_session_flash_cards.*
  into current_flash_card
  from public.game_session_flash_cards
  where game_session_flash_cards.session_id = selected_session_id
    and game_session_flash_cards.card_order =
      selected_session.current_question_order
  for update;

  if current_flash_card.status = 'active' then
    update public.game_session_flash_cards
    set
      status = 'abandoned',
      result = 'unanswered',
      resolved_at = exited_time
    where id = current_flash_card.id;
  elsif current_flash_card.status = 'submitted' then
    select game_session_flash_card_answer_keys.correct_answer
    into correct_answer
    from public.game_session_flash_card_answer_keys
    where game_session_flash_card_answer_keys.session_flash_card_id =
      current_flash_card.id;

    if not found then
      raise exception 'Flash card answer key was not found'
        using errcode = 'P0002';
    end if;

    answer_result := case
      when public.normalize_flash_card_answer(
        current_flash_card.submitted_answer
      ) = public.normalize_flash_card_answer(correct_answer)
        then 'correct'
      else 'incorrect'
    end;

    update public.game_session_flash_cards
    set
      status = 'answered',
      result = answer_result,
      resolved_at = exited_time
    where id = current_flash_card.id;
  end if;

  update public.game_session_flash_cards
  set
    status = 'not_played',
    result = 'unanswered',
    resolved_at = exited_time
  where session_id = selected_session_id
    and status = 'pending';

  update public.game_sessions
  set
    status = 'exited',
    end_reason = 'user_exit',
    ended_at = exited_time
  where id = selected_session_id;

  return public.flash_card_session_summary(
    selected_session_id,
    authenticated_user_id
  );
end;
$$;

create or replace function public.cancel_quiz_session(
  selected_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  cancelled_time timestamptz;
begin
  authenticated_user_id := public.quiz_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.session_type = 'mcq_quiz'
  for update;

  if not found then
    raise exception 'Quiz session was not found'
      using errcode = 'P0002';
  end if;

  if selected_session.status <> 'ready' then
    raise exception 'Quiz session cannot be cancelled'
      using errcode = '55000';
  end if;

  cancelled_time := clock_timestamp();

  update public.game_session_questions
  set
    status = 'cancelled',
    result = 'unanswered',
    resolved_at = cancelled_time
  where session_id = selected_session_id
    and status = 'pending';

  update public.game_sessions
  set
    status = 'cancelled',
    end_reason = 'countdown_cancelled',
    ended_at = cancelled_time
  where id = selected_session_id;

  return jsonb_build_object(
    'sessionId', selected_session_id,
    'status', 'cancelled'
  );
end;
$$;

create or replace function public.exit_quiz_session(
  selected_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  authenticated_user_id uuid;
  selected_session public.game_sessions%rowtype;
  current_question public.game_session_questions%rowtype;
  correct_option_id bigint;
  answer_result text;
  exited_time timestamptz;
begin
  authenticated_user_id := public.quiz_reviewee_user_id();

  select game_sessions.*
  into selected_session
  from public.game_sessions
  where game_sessions.id = selected_session_id
    and game_sessions.user_id = authenticated_user_id
    and game_sessions.session_type = 'mcq_quiz'
  for update;

  if not found then
    raise exception 'Quiz session was not found'
      using errcode = 'P0002';
  end if;

  if selected_session.status in ('completed', 'exited') then
    return public.quiz_session_summary(
      selected_session_id,
      authenticated_user_id
    );
  end if;

  if selected_session.status <> 'in_progress' then
    raise exception 'Quiz session cannot be exited'
      using errcode = '55000';
  end if;

  exited_time := clock_timestamp();

  select game_session_questions.*
  into current_question
  from public.game_session_questions
  where game_session_questions.session_id = selected_session_id
    and game_session_questions.question_order =
      selected_session.current_question_order
  for update;

  if current_question.status = 'active' then
    update public.game_session_questions
    set
      status = 'abandoned',
      result = 'unanswered',
      resolved_at = exited_time
    where id = current_question.id;
  elsif current_question.status = 'submitted' then
    select game_session_answer_keys.correct_option_id
    into correct_option_id
    from public.game_session_answer_keys
    where game_session_answer_keys.session_question_id =
      current_question.id;

    answer_result := case
      when current_question.selected_option_id = correct_option_id
        then 'correct'
      else 'incorrect'
    end;

    update public.game_session_questions
    set
      status = 'answered',
      result = answer_result,
      resolved_at = exited_time
    where id = current_question.id;
  end if;

  update public.game_session_questions
  set
    status = 'not_played',
    result = 'unanswered',
    resolved_at = exited_time
  where session_id = selected_session_id
    and status = 'pending';

  update public.game_sessions
  set
    status = 'exited',
    end_reason = 'user_exit',
    ended_at = exited_time
  where id = selected_session_id;

  return public.quiz_session_summary(
    selected_session_id,
    authenticated_user_id
  );
end;
$$;

revoke all on function public.flash_card_reviewee_user_id()
  from public, anon, authenticated;
revoke all on function public.normalize_flash_card_answer(text)
  from public, anon, authenticated;
revoke all on function public.flash_card_session_summary(uuid, uuid)
  from public, anon, authenticated;

revoke all on function public.prepare_flash_card_session(bigint)
  from public, anon;
revoke all on function public.start_flash_card_session(uuid)
  from public, anon;
revoke all on function public.submit_flash_card_answer(bigint, text)
  from public, anon;
revoke all on function public.reveal_flash_card_answer(bigint)
  from public, anon;
revoke all on function public.timeout_flash_card(bigint)
  from public, anon;
revoke all on function public.advance_flash_card_session(uuid)
  from public, anon;
revoke all on function public.cancel_flash_card_session(uuid)
  from public, anon;
revoke all on function public.exit_flash_card_session(uuid)
  from public, anon;

grant execute on function public.prepare_flash_card_session(bigint)
  to authenticated;
grant execute on function public.start_flash_card_session(uuid)
  to authenticated;
grant execute on function public.submit_flash_card_answer(bigint, text)
  to authenticated;
grant execute on function public.reveal_flash_card_answer(bigint)
  to authenticated;
grant execute on function public.timeout_flash_card(bigint)
  to authenticated;
grant execute on function public.advance_flash_card_session(uuid)
  to authenticated;
grant execute on function public.cancel_flash_card_session(uuid)
  to authenticated;
grant execute on function public.exit_flash_card_session(uuid)
  to authenticated;

commit;
