begin;

create table if not exists public.flash_card_decks (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid()
    references public.users(user_id) on delete cascade,
  area_id bigint not null
    references public.subject_areas(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint flash_card_decks_user_area_key unique (user_id, area_id)
);

create table if not exists public.flash_cards (
  id bigint generated by default as identity primary key,
  deck_id bigint not null
    references public.flash_card_decks(id) on delete cascade,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint flash_cards_question_check check (
    char_length(btrim(question)) between 1 and 1000
  ),
  constraint flash_cards_answer_check check (
    char_length(btrim(answer)) between 1 and 2000
  )
);

create index if not exists flash_card_decks_user_updated_at_idx
  on public.flash_card_decks(user_id, updated_at desc);

create index if not exists flash_cards_deck_created_at_idx
  on public.flash_cards(deck_id, created_at, id);

create or replace function public.enforce_flash_card_deck_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' then
    if new.deck_id = old.deck_id then
      return new;
    end if;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(new.deck_id);

  if (
    select count(*)
    from public.flash_cards
    where flash_cards.deck_id = new.deck_id
  ) >= 100 then
    raise exception 'Flash card decks can contain no more than 100 cards'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create or replace function public.touch_flash_card_deck()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.flash_card_decks
  set updated_at = now()
  where id = case when tg_op = 'DELETE' then old.deck_id else new.deck_id end;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

drop trigger if exists set_flash_card_decks_updated_at
  on public.flash_card_decks;
create trigger set_flash_card_decks_updated_at
before update on public.flash_card_decks
for each row execute function public.set_updated_at();

drop trigger if exists set_flash_cards_updated_at on public.flash_cards;
create trigger set_flash_cards_updated_at
before update on public.flash_cards
for each row execute function public.set_updated_at();

drop trigger if exists enforce_flash_card_deck_limit
  on public.flash_cards;
create trigger enforce_flash_card_deck_limit
before insert or update of deck_id on public.flash_cards
for each row execute function public.enforce_flash_card_deck_limit();

drop trigger if exists touch_flash_card_deck on public.flash_cards;
create trigger touch_flash_card_deck
after insert or update or delete on public.flash_cards
for each row execute function public.touch_flash_card_deck();

alter table public.flash_card_decks enable row level security;
alter table public.flash_cards enable row level security;

drop policy if exists "Reviewees can manage their flash card decks"
  on public.flash_card_decks;
create policy "Reviewees can manage their flash card decks"
on public.flash_card_decks
for all
to authenticated
using (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.user_roles
    join public.roles on roles.id = user_roles.role_id
    where user_roles.user_id = (select auth.uid())
      and roles.name = 'reviewee'
  )
)
with check (
  user_id = (select auth.uid())
  and exists (
    select 1
    from public.user_roles
    join public.roles on roles.id = user_roles.role_id
    where user_roles.user_id = (select auth.uid())
      and roles.name = 'reviewee'
  )
);

drop policy if exists "Reviewees can manage their flash cards"
  on public.flash_cards;
create policy "Reviewees can manage their flash cards"
on public.flash_cards
for all
to authenticated
using (
  exists (
    select 1
    from public.flash_card_decks
    join public.user_roles
      on user_roles.user_id = flash_card_decks.user_id
    join public.roles on roles.id = user_roles.role_id
    where flash_card_decks.id = flash_cards.deck_id
      and flash_card_decks.user_id = (select auth.uid())
      and roles.name = 'reviewee'
  )
)
with check (
  exists (
    select 1
    from public.flash_card_decks
    join public.user_roles
      on user_roles.user_id = flash_card_decks.user_id
    join public.roles on roles.id = user_roles.role_id
    where flash_card_decks.id = flash_cards.deck_id
      and flash_card_decks.user_id = (select auth.uid())
      and roles.name = 'reviewee'
  )
);

revoke all on table public.flash_card_decks
  from public, anon, authenticated;
revoke all on table public.flash_cards
  from public, anon, authenticated;
grant select, insert, update, delete
  on table public.flash_card_decks to authenticated;
grant select, insert, update, delete
  on table public.flash_cards to authenticated;
grant all on table public.flash_card_decks to service_role;
grant all on table public.flash_cards to service_role;

revoke all on sequence public.flash_card_decks_id_seq
  from public, anon, authenticated;
revoke all on sequence public.flash_cards_id_seq
  from public, anon, authenticated;
grant usage, select on sequence public.flash_card_decks_id_seq
  to authenticated;
grant usage, select on sequence public.flash_cards_id_seq
  to authenticated;
grant all on sequence public.flash_card_decks_id_seq to service_role;
grant all on sequence public.flash_cards_id_seq to service_role;

revoke all on function public.enforce_flash_card_deck_limit()
  from public, anon, authenticated;
revoke all on function public.touch_flash_card_deck()
  from public, anon, authenticated;

commit;
