import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { AuthProvider } from "@/features/auth/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${poppins.variable} min-h-full flex flex-col`}>
        <AuthProvider user={user}>{children}</AuthProvider>
      </body>
    </html>
  );
}
