create table if not exists public.question_sets (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  game_type text not null,
  difficulty text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint question_sets_game_type_check check (
    game_type in ('Guess the Word', 'AB-Solution', 'Situationship')
  ),
  constraint question_sets_difficulty_check check (
    difficulty in ('Easy', 'Medium', 'Hard')
  ),
  constraint question_sets_subject_game_difficulty_key unique (
    subject_id,
    game_type,
    difficulty
  )
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  question_set_id bigint not null references public.question_sets(id) on delete cascade,
  question_text text not null,
  explanation text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.question_options (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  option_text text not null,
  is_correct boolean not null default false,
  sort_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint question_options_sort_order_check check (sort_order between 1 and 4),
  constraint question_options_question_sort_order_key unique (question_id, sort_order)
);

create unique index if not exists question_options_one_correct_answer_idx
  on public.question_options(question_id)
  where is_correct;

create index if not exists question_sets_subject_id_idx
  on public.question_sets(subject_id);

create index if not exists questions_question_set_id_idx
  on public.questions(question_set_id);

create index if not exists question_options_question_id_idx
  on public.question_options(question_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_question_sets_updated_at on public.question_sets;
create trigger set_question_sets_updated_at
before update on public.question_sets
for each row execute function public.set_updated_at();

drop trigger if exists set_questions_updated_at on public.questions;
create trigger set_questions_updated_at
before update on public.questions
for each row execute function public.set_updated_at();

drop trigger if exists set_question_options_updated_at on public.question_options;
create trigger set_question_options_updated_at
before update on public.question_options
for each row execute function public.set_updated_at();

alter table public.question_sets enable row level security;
alter table public.questions enable row level security;
alter table public.question_options enable row level security;

create policy "Admins can manage question sets"
on public.question_sets
for all
to authenticated
using ('admin' = any(public.get_user_roles(auth.uid()::uuid)))
with check ('admin' = any(public.get_user_roles(auth.uid()::uuid)));

create policy "Admins can manage questions"
on public.questions
for all
to authenticated
using ('admin' = any(public.get_user_roles(auth.uid()::uuid)))
with check ('admin' = any(public.get_user_roles(auth.uid()::uuid)));

create policy "Admins can manage question options"
on public.question_options
for all
to authenticated
using ('admin' = any(public.get_user_roles(auth.uid()::uuid)))
with check ('admin' = any(public.get_user_roles(auth.uid()::uuid)));
